import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, Slide } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "gabi-arc-app",
  description: "Generated by create next app",
  icons: {
    icon: "/GL.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {children}
    //     <ToastContainer
    //       position="top-center"
    //       autoClose={3000}
    //       hideProgressBar={false}
    //       newestOnTop
    //       closeOnClick
    //       pauseOnFocusLoss
    //       draggable
    //       pauseOnHover
    //       transition={Slide} // 👈 Make sure this is defined
    //       theme="colored" // or "light", "dark"
    //     />
    //   </body>
    // </html>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          pauseOnFocusLoss
          draggable
          pauseOnHover
          transition={Slide} // 👈 Make sure this is defined
          theme="colored" // or "light", "dark"
        />
        <div className="flex flex-col min-h-screen">
          <main className="flex flex-col flex-1 bg-white">{children}</main>
        </div>
      </body>
    </html>
  );
}
